spring:
  datasource:
    url: jdbc:postgresql://db.nbxzssvjtjllfruovuvf.supabase.co:5432/postgres?sslmode=require
    username: postgres
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
