spring:
  datasource:
    url: jdbc:postgresql://db.nbxzssvjtjllfruovuvf.supabase.co:5432/postgres?sslmode=require
#    url: jdbc:mariadb://localhost:3306/volleyball
    username: root
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
    ddl-auto: validate
#  database-platform: org.hibernate.dialect.MariaDBDialect
  database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

  info:
    title: Volleyball Tournament API
    description: REST API for managing the volleyball tournament
    version: 1.0.0